<a href="https://colab.research.google.com/github/rajat459/python/blob/main/18_Dec_Advance_python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
.# Numpy --->
        # Numpy is an open source library that is used for scintific calculation

In [ ]:
# Why we use numpy whenever we have list ?
#  1> homogenous data type
#  2> memory less  consume
#  3> less time consume

In [ ]:
#  !pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=[1,34,67,90]
type(a)

list

In [ ]:
b=np.array(a)
print(b)

[ 1 34 67 90]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
# Dimension
#  1-D ==> element exist in x- direction
# 2-D ==> element exist in x and y direction
# 3-D ==> element exists in x,y,z direction

In [ ]:
print("Total Shape :",b.shape)   # shape = n(row),n(col)

Total Shape : (4,)


In [ ]:
print("Total Elements :",b.size)  # size = n(row)*n(col)

Total Elements : 4


In [ ]:
print("Total Dimension :",b.ndim)  # ndim=== dimension

Total Dimension : 1


In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
print("Total Shape :",b.shape)   # shape = n(row),n(col)
print("Total Elements :",b.size)  # size = n(row)*n(col)
print("Total Dimension :",b.ndim)

Total Shape : (3, 3)
Total Elements : 9
Total Dimension : 2


In [ ]:
# How can we create a user defined Array ?
a=[]
size=int(input("Enter size :"))
for i in range(size):
  val=int(input("Enter number: "))
  a.append(val)

b=np.array(a)
b

Enter size :4
Enter number: 12
Enter number: 56
Enter number: 78
Enter number: 2345


array([  12,   56,   78, 2345])

In [ ]:
# Numpy function -->
#               Images ==>pixels(0-255)px --> 0px(black) , 255px(white)--->normalize ==> (0-1)px

#  (A) . black&white image -- height , width
#  (B) . Colorfull Image -- height , width clor_channel((red,green , blue))
# Matrix -- n(rows) =  n(col) -- syymetric matrix
#  n(rows)!=n(col) -- asyymetric matrix
# random number genration ==> random module
# data science ==> simple line equation
#  y = mx + b  (x,y) - cordinates  m- weights  , b-- intercept
# Matrix  -- row,col
# Matrix ==> diagonal positional element --[(1,1),(2,2),(3,3)--(n,n)]

In [ ]:
# zeros() -- It will create an array in which all the values are zero


In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 2> ones()==> It will create an array in which all the values are 1

In [ ]:
a=np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a.shape

(3, 4)

In [ ]:
# 3>  eye() -- > it will create an array in which diagonal positional elements are 1 and
#  rest all are 0.

In [ ]:
a= np.eye(3)  # syymetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.eye(3,4)   # assymtric
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# 4> diag() --> It will create an array in which we can customize our diagonal positional
#  elements

In [ ]:
a = np.diag([1,2,33,456])
a

array([[  1,   0,   0,   0],
       [  0,   2,   0,   0],
       [  0,   0,  33,   0],
       [  0,   0,   0, 456]])

In [ ]:
# 5> Random module ->
# a>  Otp genration
# b> Data set ==> 1 dummy column add
# c> randomly weights initialize

In [ ]:
# A> Randint(min_number,max_number,total_number)


In [ ]:
a=np.random.randint(1,10,3)
a

array([6, 4, 2])

In [ ]:
# B> Rand(total_number) --> it will return number from 0 to 1


In [ ]:
a = np.random.rand(5)
a

array([0.53387126, 0.39282918, 0.76776692, 0.35884808, 0.19104772])

In [ ]:
# C> randn() == -3 to +3

In [ ]:
a=np.random.randn(5)
a

array([-1.58144425, -0.06914896,  0.42493759, -1.28981172, -0.22786928])

In [ ]:
# Seed() --> It will fix our data once the data has been genrated

In [ ]:
np.random.seed(20)
a=np.random.randint(1,10,3)
a

array([4, 5, 7])