<a href="https://colab.research.google.com/github/rajat459/python/blob/main/advance_python%20day%20-1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#numpy=it is an open source library that is used for scientific calculations
#why we use nummpy when we have list
#     1.homogeneous dsata type
#     2. memory less consume
#     3.less time consume
import numpy as np
a=[1,2,3,4]
type(a)
b=np.array(a)
b

array([1, 2, 3, 4])

In [7]:
type(b)

numpy.ndarray

In [9]:
#dimension==>
# 1d array --element exist in x direction
#2d aaray--element exist in x and y direction
#3d array--element exist in x,,yz direction

print("total shape",b.shape) #shape=num ber of row ands column
print("total element",b.size)# num of row multiply number of column

print("total dimension",b.ndim)#dimensions




total shape (4,)
total element 4
total shape 1


In [13]:
a=[[1,3,2],[4,5,6],[7,7,8]]
a
b=np.array(a)
b
type(b)

numpy.ndarray

In [16]:
a=[]
size=int(input("enter size"))
for i in range(size):
    val=int(input("enter number"))
    a.append(val)
b=np.array(a)
b

enter size2
enter number23
enter number56


array([23, 56])

In [21]:
a=np.diag([1,2,8,9])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [26]:

#Images ===> Pixels (0-255)px ===> 0px (black), 255px (white) ===> Normalize ===> (0-1)px
# (a). black&white image ===> height, width
# (b). Colorfull Image ===> height, width, color_channel (red, green, blue)
# Matrix ===> n(rows) = n(columns) ===> Symmatric Matrix n(r)!= n(c) ===> Asymmatric Matrix
# random number generation ===> random module
# Data Science ===> simple Line equation #Matrix ===> row, column
#Matrix ===> digonal positional elementJ= y = mx + b ## (x,y)= co-ordinates, m-weight, b=intercept=[(1,1), (2,2), (3,3)......(n,n)]

#zeros()=it will create an array in which all the values are  0
a=np.zeros(3)
a
a=np.zeros((3,4))
a
#ones==>it will create an array in which all the values are  1
a=np.ones(3)
a
a=np.ones((3,4))
a
a.shape

#eye==>it will create an array in which diagnol positional element are 1 and rest all are 0
a=np.eye(3) #symatric matrx
a
a=np.eye(3,4) #asymatirc matrix
a

#diag=>it will create an array in which customize our diagnol positional argument
a=np.diag([1,2,3,4])
a







array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:

 # (5). Random Module ====>
# (a). OTP Generation
# (b). Dataset ===> 1 dummy column add
# (c). randomly weights initialize
 # (a). Randint(min_number, max_number, total_numbers)
a = np.random.randint(1,10,3)
a
 # (b). Rand (total_numbers) ===> It will return numbers from 0 to 1
a = np.random.rand(5)
a
 # (c). Randn() ===> -3 to +3
a=np.random.randn(5)
a

#seed==>it will fix out data once the data has beeen generated

np.random.seed(20)
a=np.random.randint(1,10,3)
a

array([4, 5, 7])