<a href="https://colab.research.google.com/github/rajat459/python/blob/main/FunctionTransformer_6_feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
import numpy as np

In [ ]:
# The Function Transformer takes as input a single function that will be applied
# to each sample in the data . This function can be any python Function that takes
# a single argument, such as a lambda function or a user defined function . The
# function should return the transformed sample

In [ ]:
# create a dataset
x = np.array([[1,2],[3,4]])

#define the transformation function
log_transform = FunctionTransformer(np.log1p)

#apply the thransformation to the dataset
x_transformed = log_transform.transform(x)

#view the transformed data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
# 1 Custom Feature Engineering

from sklearn.preprocessing import FunctionTransformer

In [ ]:
import numpy as np

In [ ]:
# create a data set
x = np.array([[1,2],[3,4]])

# define a custoom feature engineering function

def holi(x):
  return np.hstack((x, x**2))

# create a FunctionTransforme to apply the custom Function
custom_transformer = FunctionTransformer(holi)

#apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

#view the transformer data
print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [ ]:
# create a data set
x = np.array([[1,2],[3,4]])

# define a custoom feature engineering function
def my_scaling(x):
  return x / np.max(x)


# create a FunctionTransforme to apply the custom Function
custom_transformer = FunctionTransformer(my_scaling)


#apply the transformer to the input data
x_transformed = custom_transformer.transform(x)


#view the transformer data
print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [ ]:
# data cleaning

# create a dataset with missing value
x = np.array([[1,2],[3,np.nan]])

# define a custoom  c;eaning function
def my_cleaning(x):
  x[np.isnan(x)] = 0
  return x


# create a FunctionTransforme to apply the custom Function
custom_transformer = FunctionTransformer(my_cleaning)


#apply the transformer to the input data
x_transformed = custom_transformer.transform(x)


#view the transformer data
print(x_transformed)

[[1. 2.]
 [3. 0.]]


In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.read_csv("/content/placement.csv")
df.head(2)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [ ]:
x = df.drop(columns = ['placed'])
y = df['placed']

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
x_transformed = log_transform.transform(x)

In [ ]:
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [ ]:
# Problem Statment

#DataSet ---> data(int , flot , object)--->
#(a). Function create ---> seprate into different list of columns(int ,flot , object)

In [ ]:
import pandas as pd
from sklearn.preprocessing import FunctionTransformer

df = pd.read_csv("/content/covid_toy.csv")
int_list = []
float_list = []
object_list = []
def separate_data(df):


    for col in df.columns:
        if df[col].dtype == 'int64':
            int_list.append(col)
        elif df[col].dtype == 'float64':
            float_list.append(col)
        else:
            object_list.append(col)

    return [int_list, float_list, object_list]


transformer = FunctionTransformer(separate_data)
result = transformer.transform(df)

print("Integer Col-:", result[0])
print("Float Col-:", result[1])
print("Object Col-:",result[2])


Integer Col-: ['age']
Float Col-: ['fever']
Object Col-: ['gender', 'cough', 'city', 'has_covid']


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
for i in object_list:
  df[i]=lb.fit_transform(df[i])
df.head(3)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0

In [ ]:
missing_df = df.isnull().sum().reset_index(name="missing")
missing_df

index  missing
0        age        0
1     gender        0
2      fever       10
3      cough        0
4       city        0
5  has_covid        0

In [ ]:
missing_col = []
for i in df.columns:
  missing=df[i].isnull().sum()
  if missing > 0:
    missing_col.append(i)
print(missing_col)

['fever']


In [ ]:
for i in missing_col:
    if i in int_list:
        from sklearn.impute import SimpleImputer
        si = SimpleImputer(strategy="mean")
        df[i] = si.fit_transform(df[[i]])
    elif i in float_list:
        from sklearn.impute import SimpleImputer
        si = SimpleImputer(strategy="mean")
        df[i] = si.fit_transform(df[[i]])

df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64