<a href="https://colab.research.google.com/github/rajat459/python/blob/main/oneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd

In [16]:
df=pd.read_csv('/content/tips.csv')

In [17]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe=OneHotEncoder()

In [20]:
ohe=OneHotEncoder(drop='first',sparse_output=False , dtype=np.int32)

In [21]:
df_new=ohe.fit_transform(df[['sex','smoker','day','time']])

In [22]:
df_new

array([[0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       ...,
       [1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]], dtype=int32)

In [24]:
df_new_2 = pd.DataFrame(df_new,columns = ['sex_f','smoker_n','t','w','th','l'])

In [25]:
df_new_2

sex_f  smoker_n  t  w  th  l
0        0         0  0  1   0  0
1        1         0  0  1   0  0
2        1         0  0  1   0  0
3        1         0  0  1   0  0
4        0         0  0  1   0  0
..     ...       ... .. ..  .. ..
239      1         0  1  0   0  0
240      0         1  1  0   0  0
241      1         1  1  0   0  0
242      1         0  1  0   0  0
243      0         0  0  0   1  0

[244 rows x 6 columns]

In [28]:
zz=pd.get_dummies(df,columns=['sex', 'smoker','day','time'], drop_first=True)

In [29]:
zz=zz.astype(int)

In [30]:
zz

total_bill  tip  size  sex_Male  smoker_Yes  day_Sat  day_Sun  day_Thur  \
0            16    1     2         0           0        0        1         0   
1            10    1     3         1           0        0        1         0   
2            21    3     3         1           0        0        1         0   
3            23    3     2         1           0        0        1         0   
4            24    3     4         0           0        0        1         0   
..          ...  ...   ...       ...         ...      ...      ...       ...   
239          29    5     3         1           0        1        0         0   
240          27    2     2         0           1        1        0         0   
241          22    2     2         1           1        1        0         0   
242          17    1     2         1           0        1        0         0   
243          18    3     2         0           0        0        0         1   

     time_Lunch  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
239           0  
240           0  
241           0  
242           0  
243           0  

[244 rows x 9 columns]

In [31]:
df=pd.read_csv('/content/covid_toy.csv')

In [32]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [33]:
from sklearn.preprocessing import LabelEncoder

In [36]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [34]:
ld=LabelEncoder()

In [37]:
df['gender']=ld.fit_transform(df['gender'])
df['cough']=ld.fit_transform(df['cough'])
df['city']=ld.fit_transform(df['city'])
df['has_covid']=ld.fit_transform(df['has_covid'])


In [38]:
df.head()

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [39]:
#ordinal enocidng
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [40]:
cf=pd.read_csv('/content/covid_toy.csv')

In [41]:
cf.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [45]:
cf=cf.drop(columns=['age', 'fever'])

In [46]:
cf.columns

Index(['gender', 'cough', 'city', 'has_covid'], dtype='object')

In [48]:
cf['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [54]:
oe=OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],[ 'Kolkata' ,'Delhi','Bangalore','Mumbai'],['Yes','No']])

In [56]:
cf_new=oe.fit_transform(cf)

In [57]:
cf_new

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 3., 1.],
       [1., 0., 2., 0.],
       [0., 1., 2., 1.],
       [1., 1., 3., 0.],
       [1., 1., 2., 1.],
       [1., 0., 1., 1.],
       [1., 0., 1., 1.],
       [1., 0., 3., 0.],
       [1., 1., 0., 1.],
       [0., 0., 2., 0.],
       [0., 0., 2., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 0., 2., 0.],
       [1., 1., 2., 0.],
       [0., 1., 2., 1.],
       [0., 0., 2., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 3., 1.],
       [1., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 1.],
       [1., 1., 3., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 3., 0.],
       [1., 1., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],


In [58]:
cf_new=pd.DataFrame(cf_new,columns=cf.columns)

In [59]:
cf_new

gender  cough  city  has_covid
0      0.0    0.0   0.0        1.0
1      0.0    0.0   1.0        0.0
2      0.0    0.0   1.0        1.0
3      1.0    0.0   0.0        1.0
4      1.0    0.0   3.0        1.0
..     ...    ...   ...        ...
95     1.0    0.0   2.0        1.0
96     1.0    1.0   0.0        0.0
97     1.0    0.0   2.0        1.0
98     1.0    1.0   3.0        1.0
99     1.0    1.0   0.0        0.0

[100 rows x 4 columns]

In [70]:
gf=pd.read_csv('/content/covid_toy.csv')

In [61]:
gf.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [63]:
gf.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [71]:
gf.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [72]:
from sklearn.impute import SimpleImputer

In [73]:
si=SimpleImputer()

In [74]:
gf['fever']=si.fit_transform(gf[['fever']])

In [75]:
ohe=OneHotEncoder(drop='first',sparse_output=False , dtype=np.int32)

In [76]:
gff_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

In [77]:
gff_new

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
 

In [78]:
bf=pd.get_dummies(gf,columns=['gender', 'cough','city','has_covid'], drop_first=True)

In [79]:
bf

age  fever  gender_Male  cough_Strong  city_Delhi  city_Kolkata  \
0    60  103.0         True         False       False          True   
1    27  100.0         True         False        True         False   
2    42  101.0         True         False        True         False   
3    31   98.0        False         False       False          True   
4    65  101.0        False         False       False         False   
..  ...    ...          ...           ...         ...           ...   
95   12  104.0        False         False       False         False   
96   51  101.0        False          True       False          True   
97   20  101.0        False         False       False         False   
98    5   98.0        False          True       False         False   
99   10   98.0        False          True       False          True   

    city_Mumbai  has_covid_Yes  
0         False          False  
1         False           True  
2         False          False  
3         False          False  
4          True          False  
..          ...            ...  
95        False          False  
96        False           True  
97        False          False  
98         True          False  
99        False           True  

[100 rows x 8 columns]

In [80]:
bf=bf.astype(int)

In [81]:
bf

age  fever  gender_Male  cough_Strong  city_Delhi  city_Kolkata  \
0    60    103            1             0           0             1   
1    27    100            1             0           1             0   
2    42    101            1             0           1             0   
3    31     98            0             0           0             1   
4    65    101            0             0           0             0   
..  ...    ...          ...           ...         ...           ...   
95   12    104            0             0           0             0   
96   51    101            0             1           0             1   
97   20    101            0             0           0             0   
98    5     98            0             1           0             0   
99   10     98            0             1           0             1   

    city_Mumbai  has_covid_Yes  
0             0              0  
1             0              1  
2             0              0  
3             0              0  
4             1              0  
..          ...            ...  
95            0              0  
96            0              1  
97            0              0  
98            1              0  
99            0              1  

[100 rows x 8 columns]