<a href="https://colab.research.google.com/github/rajat459/python/blob/main/test_of_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Q.1 = Write statement to import numpy ?
import numpy as np

In [35]:
#2
array=np.random.rand(2,3)
array

array([[0.32898019, 0.29756906, 0.52431821],
       [0.55851233, 0.5618299 , 0.76292019]])

In [21]:
#3
array=np.random.randint(0,3,3)
array

array([0, 2, 0])

In [29]:
#4
array = np.arange(10, 21)
print(array)



[10 11 12 13 14 15 16 17 18 19 20]


In [30]:
#5
a=np.repeat(8,10)
a

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [33]:
#6
matrix = np.arange(0,12).reshape((4,3))
matrix


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
array = np.random.rand(3, 3)
print(array)


[[0.1016851  0.61486017 0.44380753]
 [0.83684995 0.75155674 0.24231639]
 [0.01324249 0.71402642 0.50290474]]


In [28]:
#8
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

np.concatenate((array1, array2))
np.hstack((array1, array2))

np.concatenate((array1, array2))
np.vstack((array1, array2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
#Q.9 difference between zeros() , ones() , eye() , diag() , linspace() , unique() , random(randint() , rand()) with example.

#zeros gives a matrix where all values are 0
a=np.zeros((3,3))
a
#ones--->ones gives a matrix where all values are 1
b=np.ones((3,3))
b
#eye---> it gives an indentital matrix.
c=np.eye(3,3)
c
# diag--> it gives the array in which in diagnol position of any number are given and others are 0
d=np.diag((3,3))
d
# linspcae --> it gives an equal gaps of number in the given range
e=np.linspace(0,10,5)
e
#unique --> it gives an unique vlaue and then it process it count and gives index
f=np.unique([2,3,4,5,6])
f
# random rand ---- it gives random value btw 0 and 1 and float
array=np.random.rand(3,3)
array
# random rand int -- it gives vlaue in range btw given
array=np.random.randint(0,3,3)
array

array([2, 3, 4, 5, 6])

In [25]:
# 10
# horizontol stack --- in which it turns the array in horizontol form
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))
# v stcak---> in which it turns the array in vertical form
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# 11
# view-- when we use view the data we have changed it directly changed in our orginal data.
new = np.array([1, 2, 3])

view1 = new
copy1 = new.copy()

new[0] = 10

print(new)
print( view1)
print( copy1)


[10  2  3]
[10  2  3]
[1 2 3]
